services:
  # Base de données PostgreSQL
  - type: pserv
    name: privalead-database
    plan: free
    databaseName: privalead_db
    user: privalead_user

  # Backend API avec LinkedIn
  - type: web
    name: privalead-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: privalead-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: LINKEDIN_CLIENT_ID
        value: "86occjps58doir"
      - key: LINKEDIN_CLIENT_SECRET
        value: "WPL_AP1.C8C6uXjTbpJyQUx2.Y7COPg=="
      - key: LINKEDIN_REDIRECT_URI
        value: "https://privalead-1.onrender.com/api/linkedin/callback"
      - key: GEMINI_API_KEY
        value: "AIzaSyB434P__wR_o_rr5Q3PjOULqyKhMANRtgk"
      - key: NEWS_API_KEY
        value: "2cc0499903c24433a7646123cb3a82e0"
      - key: FRONTEND_URL
        value: "https://privalead-1.onrender.com"
    healthCheckPath: "/api/health"

  # Frontend React
  - type: web
    name: privalead-frontend
    env: static
    region: frankfurt
    plan: free
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "./build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://privalead-1.onrender.com/api"
      - key: REACT_APP_LINKEDIN_CLIENT_ID
        value: "86occjps58doir"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
