services:
  # Backend API Flask
  - type: web
    name: linkedboost-backend
    env: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --config gunicorn.conf.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: linkedboost-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: "production"
      - key: LINKEDIN_CLIENT_ID
        value: "86occjps58doir"
      - key: LINKEDIN_CLIENT_SECRET
        value: "WPL_AP1.C8C6uXjTbpJyQUx2.Y7COPg=="
      - key: LINKEDIN_REDIRECT_URI
        value: "https://linkedboost-frontend.onrender.com/callback"
      - key: GEMINI_API_KEY
        value: "AIzaSyB434P__wR_o_rr5Q3PjOULqyKhMANRtgk"
      - key: NEWS_API_KEY
        value: "2cc0499903c24433a7646123cb3a82e0"
      - key: FRONTEND_URL
        value: "https://linkedboost-frontend.onrender.com"
      - key: CORS_ORIGINS
        value: "https://linkedboost-frontend.onrender.com,http://localhost:3000"
